---
- hosts: workstation
  become: yes
  pre_tasks:
    - name: Load host_vars for local workstation
      include_vars: "host_vars/{{ ansible_hostname }}.yml"
      tags:
        - always

    - name: Ensure workstation groups exist
      group:
        name: "{{ item.name }}"
        system: "{{ item.system }}"
        state: present
      loop: "{{ workstation_groups | flatten(levels=1) }}"
      when: workstation_groups is defined
      tags:
        - always

    - name: Update user groups
      user:
        name: "{{ ansible_user }}"
        groups: "{{ workstation_user_groups }}"
        append: yes
      when: workstation_user_groups is defined
      tags:
        - always
  roles:
    - role: weareinteractive.apt
      when: workstation_run_apt_play
      tags:
        - packages
        - apt

    - role: wtanaka.slack
      when: workstation_run_slack_play
      tags:
        - communication
        - slack

    - role: jkglasbrenner.environment_modules
      when: workstation_run_environment_modules_play
      tags:
        - configuration
        - modules

    - role: franklinkim.ufw
      when: workstation_run_firewall_play
      tags:
        - firewall
        - security

    - role: joshualund.golang
      when: workstation_run_golang_play
      tags:
        - languages
        - go

    - role: jkglasbrenner.miniconda
      when: workstation_run_miniconda_play
      tags:
        - languages
        - python
        - miniconda
        - aiida

    - role: andrewrothstein.virtualbox
      when: workstation_run_virtualbox_play
      tags:
        - virtualization
        - virtualbox

    - role: andrewrothstein.vagrant
      when: workstation_run_vagrant_play
      tags:
        - virtualization
        - vagrant

    - role: angstwad.docker_ubuntu
      when: workstation_run_docker_play
      tags:
        - virtualization
        - docker
  tasks:
    - name: Install ripgrep
      apt:
        deb: "{{ ripgrep_deb_url }}"
      when: workstation_run_ripgrep_play
      tags:
        - packages
        - apt
...
