---
aiida_aiidadb_password: "{{ vault_aiida_aiidadb_password }}"
apt_packages:
  - aptitude
  - arc-theme
  - audacity
  - automake
  - build-essential
  - chrome-gnome-shell
  - clang
  - clang-format
  - clang-tidy
  - clang-tools
  - cmake
  - default-jre
  - emacs-snapshot
  - gdebi
  - gimp
  - git
  - git-crypt
  - git-flow
  - git-lfs
  - gnome-shell-extensions
  - gnome-shell-extension-redshift
  - gnome-tweaks
  - gnupg
  - gnupg-agent
  - inkscape
  - insync
  - keepass2
  - keepass2-plugin-keepasshttp
  - ledger
  - libtool
  - libcanberra-gtk-module
  - libclang-dev
  - libcurl4-openssl-dev
  - libevent-dev
  - libgdal-dev
  - libgtk2.0-dev
  - libopenbabel-dev
  - libncurses5-dev
  - libpng-dev
  - libpoppler-dev
  - libpoppler-cpp-dev
  - libpoppler-glib-dev
  - libpoppler-private-dev
  - libssl-dev
  - libudunits2-dev
  - libusb-1.0-0-dev
  - libutempter-dev
  - libyubikey-dev
  - libz-dev
  - mono-complete
  - mono-devel
  - network-manager-openconnect
  - network-manager-openconnect-gnome
  - numix-gtk-theme
  - numix-icon-theme
  - numix-icon-theme-circle
  - obs-studio
  - openbabel
  - openbabel-gui
  - openconnect
  - libreoffice-java-common
  - pcscd
  - pcsc-tools
  - pdf2svg
  - pigz
  - pinentry-curses
  - pinentry-gnome3
  - pkg-config
  - pop-theme
  - proj-bin
  - python-gpg
  - python-pexpect
  - python3-gpg
  - r-base
  - r-base-dev
  - scdaemon
  - shutter
  - silversearcher-ag
  - sni-qt
  - software-properties-common
  - sshfs
  - swig
  - telegram
  - tmux
  - unison
  - unison-gtk
  - variety
  - vim
  - winehq-devel
  - xclip
  - xdotool
  - yubico-piv-tool
  - yubikey-manager
  - yubikey-manager-qt
  - yubikey-personalization
  - yubikey-personalization-gui
  - yubikey-piv-manager
  - yubioath-desktop
  - zotero-standalone
apt_repositories:
  - "deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ansible_distribution_release }} main"
# - deb http://dl.google.com/linux/chrome/deb/ stable main
  - "deb https://dl.winehq.org/wine-builds/ubuntu/ artful main"
  - "deb https://download.mono-project.com/repo/ubuntu stable-{{ ansible_distribution_release }} main"
  - "deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}-cran35/"
  - "deb http://apt.insynchq.com/ubuntu {{ ansible_distribution_release }} non-free contrib"
  - ppa:atareao/telegram
  - ppa:jtaylor/keepass
  - ppa:mbudde/ledger
  - ppa:numix/ppa
  - ppa:obsproject/obs-studio
  - ppa:otto-kesselgulasch/gimp
  - ppa:smathot/cogscinl
  - ppa:system76/pop
  - ppa:ubuntu-elisp/ppa
  - ppa:ubuntuhandbook1/audacity
  - ppa:yubico/stable
apt_keys:
  - url: https://dl.google.com/linux/linux_signing_key.pub
  - url: https://dl.winehq.org/wine-builds/Release.key
  - keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
  - keyserver: keyserver.ubuntu.com
    id: ACCAF35C
  - keyserver: keyserver.ubuntu.com
    id: BC7345F522079769F5BBE987EFC71127F425E228
direnv:
  version: 2.16.0
  bin_sha256: a4faa0843c01ee64e4981b30101dc620623db52ce788e2730be005164dcfd8fb
  arch: direnv.linux-amd64
  base_url: https://github.com/direnv/direnv/releases/download
  dest: '{{ lookup("env", "HOME") }}/.local/stow'
hyper_term_deb_url: "https://releases.hyper.is/download/deb"
jetbrains_toolbox_version: 1.9.3935
jetbrains_toolbox_filename: "jetbrains-toolbox-{{ jetbrains_toolbox_version }}"
jetbrains_toolbox_url: "https://download.jetbrains.com/toolbox/{{ jetbrains_toolbox_filename }}.tar.gz"
keechallenge_version: 1.5
keechallenge_zip_sha256: 7a691e37858bee3a69ba81ed1c7ce6dd42de4096dfe9cd7b7547566399d3f369
keechallenge_dll_sha256: 83db8598afd595473b8d6f0ea8c2794c0a67e8dec30958eef415d063c0f0aa83
keechallenge_plugins_directory: "/usr/lib/keepass2/Plugins"
keechallenge_tmp_directory: "/tmp"
modules_use_own_dir: ".local/Modules"
modules_example_modulefiles_to_remove:
  - dot
  - module-git
  - module-info
  - "{{ 'null' }}"
modules_version: 4.1.2
nvm_version: 0.33.11
nvm_script_url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
pandoc_version: 2.2.2
pandoc_deb_url: "https://github.com/jgm/pandoc/releases/download/{{ pandoc_version }}/pandoc-{{ pandoc_version }}-1-amd64.deb"
imaginary_teleprompter_version: 2.3.4
imaginary_teleprompter_deb_url: "https://github.com/ImaginarySense/Teleprompter-Electron/releases/download/{{ imaginary_teleprompter_version }}/imaginary-teleprompter-{{ imaginary_teleprompter_version }}-64bit.deb"
ripgrep_version: 0.8.1
ripgrep_deb_url: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}_amd64.deb"
rstudio_version: 1.2.792
rstudio_deb_url: "https://s3.amazonaws.com/rstudio-ide-build/desktop/trusty/amd64/rstudio-{{ rstudio_version }}-amd64.deb"
rstudio_deb_md5: dd067d0ddfa7f77df4e177b2e3112a30
shutter_ubuntu1804_dependencies_deb_urls:
  - "https://launchpad.net/ubuntu/+archive/primary/+files/libgoocanvas-common_1.0.0-1_all.deb"
  - "https://launchpad.net/ubuntu/+archive/primary/+files/libgoocanvas3_1.0.0-1_amd64.deb"
  - "https://launchpad.net/ubuntu/+archive/primary/+files/libgoo-canvas-perl_0.06-2ubuntu3_amd64.deb"
texlive_dir: "/opt/texlive"
texlive_version: 2018
texlive_user_config_dir: "~/.config"
texlive_user_home_dir: "~/texmf"
texlive_installer_dir: "/tmp/install-tl-{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
texlive_url: "http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"
toggl_desktop_version: 7.4.122
toggl_desktop_arch: amd64
toggl_desktop_dependencies:
  - libgstreamer0.10-0
  - libgstreamer-plugins-base0.10-0
toggl_desktop_deb_url: "https://github.com/toggl/toggldesktop/releases/download/v{{ toggl_desktop_version }}/toggldesktop_{{ toggl_desktop_version }}_{{ toggl_desktop_arch }}.deb"
toggl_desktop_deb_urls:
  - "http://fr.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base0.10/libgstreamer-plugins-base0.10-0_0.10.36-1_{{ toggl_desktop_arch }}.deb"
  - "http://fr.archive.ubuntu.com/ubuntu/pool/universe/g/gstreamer0.10/libgstreamer0.10-0_0.10.36-1.5ubuntu1_{{ toggl_desktop_arch }}.deb"
  - "https://github.com/toggl/toggldesktop/releases/download/v{{ toggl_desktop_version }}/toggldesktop_{{ toggl_desktop_version }}_{{ toggl_desktop_arch }}.deb"
ufw_applications:
 - name: cups
ufw_reset: no
veracrypt_version: 1.22
veracrypt_tar_name: "veracrypt-{{ veracrypt_version }}-setup"
veracrypt_base_url: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}/+download"
veracrypt_tar_url: "{{ veracrypt_base_url }}/{{ veracrypt_tar_name }}.tar.bz2"
veracrypt_tar_sig: "{{ veracrypt_base_url }}/{{ veracrypt_tar_name }}.tar.bz2.sig"
veracrypt_arch: "x64"
veracrypt_installer: "veracrypt-{{ veracrypt_version }}-setup-console-{{ veracrypt_arch }}"
virtualbox_key_url: http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc
virtualbox_key_id: 2980AECF
virtualbox_version: 5.2

# Activate/deactivate plays
workstation_run_apt_play: true
workstation_run_slack_play: true
workstation_run_environment_modules_play: true
workstation_run_firewall_play: true
workstation_run_golang_play: true
workstation_run_miniconda_play: true
workstation_run_virtualbox_play: true
workstation_run_vagrant_play: true
workstation_run_docker_play: true
workstation_run_ripgrep_play: true
workstation_run_toggl_play: true
workstation_run_rstudio_play: true
workstation_run_pandoc_play: true
workstation_run_jetbrains_play: true
workstation_run_nvm_play: true
workstation_run_imaginary_teleprompter_play: true
workstation_run_texlive_installer_play: true
workstation_run_veracrypt_play: false
matsci_run_aiida_play: false
...
