---
aiida_aiidadb_password: "{{ vault_aiida_aiidadb_password }}"
apt_packages:
  - 2to3
  - aptitude
  - arc-theme
  - audacity
  - automake
  - build-essential
  - chrome-gnome-shell
  - clang
  - clang-format
  - clang-tidy
  - clang-tools
  - cmake
  - default-jdk
  - default-jre
  - dos2unix
  - emacs-snapshot
  - enscript
  - fasd
  - ffmpeg
  - fuse
  - fuse-convmvfs
  - gdebi
  - gimp
  - git
  - git-crypt
  - git-flow
  - git-lfs
  - gnome-calculator
  - gnome-shell-extension-redshift
  - gnome-shell-extensions
  - gnome-tweaks
  - gnupg
  - gnupg-agent
  - gstreamer1.0-libav
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-ugly
  - gstreamer1.0-pulseaudio
  - gucharmap
  - htop
  - inkscape
  - insync
  - intel-mkl-64bit-2019.1-053
  - keepass2
  - keepass2-plugin-keepasshttp
  - ledger
  - libboost-all-dev
  - libcanberra-gtk-module
  - libclang-dev
  - libcurl4-openssl-dev
  - libdvd-pkg
  - libdvdnav4
  - libdvdread4
  - libevent-dev
  - libfuse-dev
  - libgdal-dev
  - libgirepository1.0-dev
  - libglibmm-2.4-dev
  - libgmime-2.6-dev
  - libgmime-3.0-dev
  - libgtk2.0-dev
  - libgtkmm-3.0-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libnotmuch-dev
  - libntfs-3g88
  - libopenbabel-dev
  - libpeas-dev
  - libperl-dev
  - libpng-dev
  - libpoppler-cpp-dev
  - libpoppler-dev
  - libpoppler-glib-dev
  - libpoppler-private-dev
  - libprotobuf-dev
  - libreoffice-java-common
  - libsass-dev
  - libssl-dev
  - libtool
  - libudunits2-dev
  - libusb-1.0-0-dev
  - libutempter-dev
  - libv8-dev
  - libvte-2.91-dev
  - libwebkit2gtk-4.0-dev
  - libyubikey-dev
  - libz-dev
  - mc
  - mercurial
  - mercurial-git
  - mono-complete
  - mono-devel
  - mpi-default-dev
  - mtr
  - network-manager-openconnect
  - network-manager-openconnect-gnome
  - ninja-build
  - nnn
  - ntfs-3g-dev
  - numix-gtk-theme
  - numix-icon-theme
  - numix-icon-theme-circle
  - obs-studio
  - openbabel
  - openbabel-gui
  - openconnect
  - openmpi-bin
  - pcsc-tools
  - pcscd
  - pdf2svg
  - pigz
  - pinentry-curses
  - pinentry-gnome3
  - pkg-config
  - pop-theme
  - ppa-purge
  - proj-bin
  - protobuf-compiler
  - pydf
  - python-gpg
  - python-pexpect
  - python3-dev
  - python3-gpg
  - python3-proselint
  - r-base
  - r-base-dev
  - rename
  - ruby-ronn
  - scdaemon
  - scons
  - shutter
  - silversearcher-ag
  - sni-qt
  - software-properties-common
  - spotify-client
  - sshfs
  - swig
  - telegram
  - ttf-mscorefonts-installer
  - ubuntu-restricted-extras
  - unison
  - unison-gtk
  - variety
  - vim
  - vim-gtk3
  - vlc
  - winehq-devel
  - xclip
  - xdotool
  - yubico-piv-tool
  - yubikey-manager
  - yubikey-manager-qt
  - yubikey-personalization
  - yubikey-personalization-gui
  - yubikey-piv-manager
  - yubioath-desktop
  - zotero-standalone
apt_repositories:
  - "deb http://apt.insynchq.com/ubuntu {{ ansible_distribution_release }} non-free contrib"
  - "deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ansible_distribution_release }} main"
  - "deb http://repository.spotify.com stable non-free"
  - "deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}-cran35/"
  - "deb https://dl.winehq.org/wine-builds/ubuntu/ artful main"
  - "deb https://download.mono-project.com/repo/ubuntu stable-{{ ansible_distribution_release }} main"
  - "deb https://apt.repos.intel.com/mkl all main"
# - deb http://dl.google.com/linux/chrome/deb/ stable main
# - ppa:aacebedo/fasd
  - ppa:atareao/telegram
  - ppa:jtaylor/keepass
  - ppa:maarten-fonville/protobuf
  - ppa:mbudde/ledger
  - ppa:numix/ppa
  - ppa:obsproject/obs-studio
  - ppa:otto-kesselgulasch/gimp
  - ppa:smathot/cogscinl
  - ppa:system76/pop
  - ppa:twodopeshaggy/jarun
  - ppa:ubuntu-elisp/ppa
  - ppa:ubuntuhandbook1/audacity
  - ppa:yubico/stable
apt_keys:
  - url: https://dl.google.com/linux/linux_signing_key.pub
  - url: https://dl.winehq.org/wine-builds/Release.key
  - url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
  - keyserver: keyserver.ubuntu.com
    id: ACCAF35C
  - keyserver: keyserver.ubuntu.com
    id: BC7345F522079769F5BBE987EFC71127F425E228
  - keyserver: keyserver.ubuntu.com
    id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
cctools_version: 7.0.4
cctools_build_dir: "/tmp"
cctools_install_dir: "/opt/cctools/gcc/{{ cctools_version }}"
cctools_url: "https://github.com/cooperative-computing-lab/cctools/archive/release/{{ cctools_version }}.tar.gz"
cctools_unarchived_dir: "cctools-release-{{ cctools_version }}"
direnv:
  version: 2.16.0
  bin_sha256: a4faa0843c01ee64e4981b30101dc620623db52ce788e2730be005164dcfd8fb
  arch: direnv.linux-amd64
  base_url: https://github.com/direnv/direnv/releases/download
  dest: '{{ lookup("env", "HOME") }}/.local/stow'
github_classroom_assistant_version: 1.0.1
github_classroom_assistant_deb_url: "https://github.com/education/classroom-assistant/releases/download/v{{ github_classroom_assistant_version }}/classroom-assistant_{{ github_classroom_assistant_version }}_amd64.deb"
github_desktop_linux_version: "1.6.0-linux1"
github_desktop_linux_deb_url: "https://github.com/shiftkey/desktop/releases/download/release-{{ github_desktop_linux_version }}/GitHubDesktop-linux-{{ github_desktop_linux_version }}.deb"
gitkraken_arch: amd64
gitkraken_deb_url: "https://release.gitkraken.com/linux/gitkraken-{{ gitkraken_arch }}.deb"
hyper_term_deb_url: "https://releases.hyper.is/download/deb"
jetbrains_toolbox_version: 1.9.3935
jetbrains_toolbox_filename: "jetbrains-toolbox-{{ jetbrains_toolbox_version }}"
jetbrains_toolbox_url: "https://download.jetbrains.com/toolbox/{{ jetbrains_toolbox_filename }}.tar.gz"
keechallenge_version: 1.5
keechallenge_zip_sha256: 7a691e37858bee3a69ba81ed1c7ce6dd42de4096dfe9cd7b7547566399d3f369
keechallenge_dll_sha256: 83db8598afd595473b8d6f0ea8c2794c0a67e8dec30958eef415d063c0f0aa83
keechallenge_plugins_directory: "/usr/lib/keepass2/Plugins"
keechallenge_tmp_directory: "/tmp"
modules_use_own_dir: ".local/Modules"
modules_example_modulefiles_to_remove:
  - dot
  - module-git
  - module-info
  - "{{ 'null' }}"
modules_version: 4.1.2
notable_version: 1.2.0
notable_desktop_arch: amd64
notable_deb_url: "https://github.com/fabiospampinato/notable/releases/download/v{{ notable_version }}/notable_{{ notable_version }}_{{ notable_desktop_arch }}.deb"
nvm_version: 0.33.11
nvm_script_url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
pandoc_version: 2.2.2
pandoc_deb_url: "https://github.com/jgm/pandoc/releases/download/{{ pandoc_version }}/pandoc-{{ pandoc_version }}-1-amd64.deb"
imaginary_teleprompter_version: 2.3.4
imaginary_teleprompter_deb_url: "https://github.com/ImaginarySense/Teleprompter-Electron/releases/download/{{ imaginary_teleprompter_version }}/imaginary-teleprompter-{{ imaginary_teleprompter_version }}-64bit.deb"
ripgrep_version: 0.8.1
ripgrep_deb_url: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}_amd64.deb"
rstudio_version: 1.2.1139
rstudio_deb_url: "https://s3.amazonaws.com/rstudio-ide-build/desktop/trusty/amd64/rstudio-{{ rstudio_version }}-amd64.deb"
rstudio_deb_md5: 79d0627b42d6f429b2ed3708373f190a
shutter_ubuntu1804_dependencies_deb_urls:
  - "https://launchpad.net/ubuntu/+archive/primary/+files/libgoocanvas-common_1.0.0-1_all.deb"
  - "https://launchpad.net/ubuntu/+archive/primary/+files/libgoocanvas3_1.0.0-1_amd64.deb"
  - "https://launchpad.net/ubuntu/+archive/primary/+files/libgoo-canvas-perl_0.06-2ubuntu3_amd64.deb"
texlive_dir: "/opt/texlive"
texlive_version: 2018
texlive_user_config_dir: "~/.config"
texlive_user_home_dir: "~/texmf"
texlive_installer_dir: "/tmp/install-tl-{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
texlive_url: "http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"
toggl_desktop_version: 7.4.122
toggl_desktop_arch: amd64
toggl_desktop_dependencies:
  - libgstreamer0.10-0
  - libgstreamer-plugins-base0.10-0
toggl_desktop_deb_url: "https://github.com/toggl/toggldesktop/releases/download/v{{ toggl_desktop_version }}/toggldesktop_{{ toggl_desktop_version }}_{{ toggl_desktop_arch }}.deb"
toggl_desktop_deb_urls:
  - "http://fr.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base0.10/libgstreamer-plugins-base0.10-0_0.10.36-1_{{ toggl_desktop_arch }}.deb"
  - "http://fr.archive.ubuntu.com/ubuntu/pool/universe/g/gstreamer0.10/libgstreamer0.10-0_0.10.36-1.5ubuntu1_{{ toggl_desktop_arch }}.deb"
  - "https://github.com/toggl/toggldesktop/releases/download/v{{ toggl_desktop_version }}/toggldesktop_{{ toggl_desktop_version }}_{{ toggl_desktop_arch }}.deb"
ufw_applications:
 - name: cups
ufw_reset: no
veracrypt_version: 1.22
veracrypt_tar_name: "veracrypt-{{ veracrypt_version }}-setup"
veracrypt_base_url: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}/+download"
veracrypt_tar_url: "{{ veracrypt_base_url }}/{{ veracrypt_tar_name }}.tar.bz2"
veracrypt_tar_sig: "{{ veracrypt_base_url }}/{{ veracrypt_tar_name }}.tar.bz2.sig"
veracrypt_arch: "x64"
veracrypt_installer: "veracrypt-{{ veracrypt_version }}-setup-console-{{ veracrypt_arch }}"
virtualbox_key_url: http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc
virtualbox_key_id: 2980AECF
virtualbox_version: 5.2

# Activate/deactivate plays
workstation_run_apt_play: true
workstation_run_slack_play: true
workstation_run_environment_modules_play: true
workstation_run_firewall_play: true
workstation_run_golang_play: true
workstation_run_miniconda_play: true
workstation_run_virtualbox_play: true
workstation_run_vagrant_play: true
workstation_run_docker_play: true
workstation_run_ripgrep_play: true
workstation_run_toggl_play: true
workstation_run_rstudio_play: true
workstation_run_pandoc_play: true
workstation_run_jetbrains_play: true
workstation_run_notable_play: true
workstation_run_nvm_play: true
workstation_run_imaginary_teleprompter_play: true
workstation_run_texlive_installer_play: true
workstation_run_cctools_play: true
workstation_run_veracrypt_play: false
workstation_run_hyper_play: true
workstation_run_gitkraken_play: true
workstation_run_github_classroom_assistant_play: true
workstation_run_github_desktop_linux_play: true
matsci_run_aiida_play: false
...
