---
# Host-specific configuration
workstation_groups:
  - name: ansible
    system: true
  - name: docker
    system: true

workstation_user_groups:
  - "{{ ansible_user }}"
  - adm
  - ansible
  - audio
  - cdrom
  - datashare
  - dip
  - docker
  - lpadmin
  - plugdev
  - pulse
  - pulse-access
  - scanner
  - sudo
  - vboxusers
  - video

# Activate/deactivate plays
workstation_run_apt_play: false
workstation_run_slack_play: false
workstation_run_environment_modules_play: false
workstation_run_firewall_play: false
workstation_run_golang_play: false
workstation_run_miniconda_play: true
workstation_run_virtualbox_play: false
workstation_run_vagrant_play: false
workstation_run_docker_play: false
databases_run_postgresql_play: true
matsci_run_aiida_play: true
...
