---
- hosts: local
  become: no
  tasks:
    - name: Install spacemacs
      become: no
      git:
        repo: "https://github.com/syl20bnr/spacemacs"
        dest: "{{ ansible_env.HOME }}/.emacs.d"

